#!/bin/bash


### PDC-001 ###

# Set variables
#
TITLE="PDC-001"


# Clear executions
#
sudo docker exec hubdb mongo query_composer_development --eval "db.queries.update({ title : "PDC-001" },{ $set :{ executions : [] }}, {} );"


# Run query importer
#
#npm install mongodb -g
#npm link mongodb
#sudo docker exec composer ...


#Execution of Master Reports
#The following are commands for executing the PDC-001 master reports, these will work for PDC-1740 and
#PDC-1738 as well.
#Delete executions for PDC-001:
#db.queries.update({title : "PDC-001"}, { $set : { executions : [] }}, {});
#Run query importer in composer container:
#QUERY_TITLE=PDC-001 RETRO_QUERY_TITLE=Retro-PDC-001 node demographicsImporter.js
#FNW Group: \"FNW-attachment\"
#Generate report in HAPI ( /app/lib/util ):
#QUERY=PDC-001 GROUP=\"FNW-attachment\" EXECUTION_DATE=24 node generateReports.js
#Aside: autogenerated, downloadable reports located in: /app/lib/reports
